<?php
/**
 * TimesheetConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Read our [API documentation](https://www.kimai.org/documentation/rest-api.html) and download the [Open API definition](doc.json) to import into your API client.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * TimesheetConfigTest Class Doc Comment
 *
 * @category    Class
 * @description TimesheetConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TimesheetConfigTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TimesheetConfig"
     */
    public function testTimesheetConfig()
    {
    }

    /**
     * Test attribute "tracking_mode"
     */
    public function testPropertyTrackingMode()
    {
    }

    /**
     * Test attribute "default_begin_time"
     */
    public function testPropertyDefaultBeginTime()
    {
    }

    /**
     * Test attribute "active_entries_hard_limit"
     */
    public function testPropertyActiveEntriesHardLimit()
    {
    }

    /**
     * Test attribute "is_allow_future_times"
     */
    public function testPropertyIsAllowFutureTimes()
    {
    }

    /**
     * Test attribute "is_allow_overlapping"
     */
    public function testPropertyIsAllowOverlapping()
    {
    }
}
