<?php
/**
 * ActionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Read our [API documentation](https://www.kimai.org/documentation/rest-api.html) and download the [Open API definition](doc.json) to import into your API client.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ActionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ActionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getGetActivityActions
     *
     * Get all item actions for the given Activity [for internal use].
     *
     */
    public function testGetGetActivityActions()
    {
    }

    /**
     * Test case for getGetCustomerActions
     *
     * Get all item actions for the given Customer [for internal use].
     *
     */
    public function testGetGetCustomerActions()
    {
    }

    /**
     * Test case for getGetProjectActions
     *
     * Get all item actions for the given Project [for internal use].
     *
     */
    public function testGetGetProjectActions()
    {
    }

    /**
     * Test case for getGetTimesheetActions
     *
     * Get all item actions for the given Timesheet [for internal use].
     *
     */
    public function testGetGetTimesheetActions()
    {
    }
}
