<?php
/**
 * ActivityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Read our [API documentation](https://www.kimai.org/documentation/rest-api.html) and download the [Open API definition](doc.json) to import into your API client.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ActivityApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ActivityApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteDeleteActivityRate
     *
     * Deletes one rate for an activity.
     *
     */
    public function testDeleteDeleteActivityRate()
    {
    }

    /**
     * Test case for getGetActivities
     *
     * Returns a collection of activities (which are visible to the user).
     *
     */
    public function testGetGetActivities()
    {
    }

    /**
     * Test case for getGetActivity
     *
     * Returns one activity.
     *
     */
    public function testGetGetActivity()
    {
    }

    /**
     * Test case for getGetActivityRates
     *
     * Returns a collection of all rates for one activity.
     *
     */
    public function testGetGetActivityRates()
    {
    }

    /**
     * Test case for patchAppApiActivityMeta
     *
     * Sets the value of a meta-field for an existing activity.
     *
     */
    public function testPatchAppApiActivityMeta()
    {
    }

    /**
     * Test case for patchPatchActivity
     *
     * Update an existing activity.
     *
     */
    public function testPatchPatchActivity()
    {
    }

    /**
     * Test case for postPostActivity
     *
     * Creates a new activity.
     *
     */
    public function testPostPostActivity()
    {
    }

    /**
     * Test case for postPostActivityRate
     *
     * Adds a new rate to an activity.
     *
     */
    public function testPostPostActivityRate()
    {
    }
}
