<?php
/**
 * CustomerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Read our [API documentation](https://www.kimai.org/documentation/rest-api.html) and download the [Open API definition](doc.json) to import into your API client.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteDeleteCustomerRate
     *
     * Deletes one rate for a customer.
     *
     */
    public function testDeleteDeleteCustomerRate()
    {
    }

    /**
     * Test case for getGetCustomer
     *
     * Returns one customer.
     *
     */
    public function testGetGetCustomer()
    {
    }

    /**
     * Test case for getGetCustomerRates
     *
     * Returns a collection of all rates for one customer.
     *
     */
    public function testGetGetCustomerRates()
    {
    }

    /**
     * Test case for getGetCustomers
     *
     * Returns a collection of customers (which are visible to the user).
     *
     */
    public function testGetGetCustomers()
    {
    }

    /**
     * Test case for patchAppApiCustomerMeta
     *
     * Sets the value of a meta-field for an existing customer.
     *
     */
    public function testPatchAppApiCustomerMeta()
    {
    }

    /**
     * Test case for patchPatchCustomer
     *
     * Update an existing customer.
     *
     */
    public function testPatchPatchCustomer()
    {
    }

    /**
     * Test case for postPostCustomer
     *
     * Creates a new customer.
     *
     */
    public function testPostPostCustomer()
    {
    }

    /**
     * Test case for postPostCustomerRate
     *
     * Adds a new rate to a customer.
     *
     */
    public function testPostPostCustomerRate()
    {
    }
}
