<?php
/**
 * ProjectApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Read our [API documentation](https://www.kimai.org/documentation/rest-api.html) and download the [Open API definition](doc.json) to import into your API client.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProjectApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteDeleteProjectRate
     *
     * Deletes one rate for a project.
     *
     */
    public function testDeleteDeleteProjectRate()
    {
    }

    /**
     * Test case for getGetProject
     *
     * Returns one project.
     *
     */
    public function testGetGetProject()
    {
    }

    /**
     * Test case for getGetProjectRates
     *
     * Returns a collection of all rates for one project.
     *
     */
    public function testGetGetProjectRates()
    {
    }

    /**
     * Test case for getGetProjects
     *
     * Returns a collection of projects (which are visible to the user).
     *
     */
    public function testGetGetProjects()
    {
    }

    /**
     * Test case for patchAppApiProjectMeta
     *
     * Sets the value of a meta-field for an existing project.
     *
     */
    public function testPatchAppApiProjectMeta()
    {
    }

    /**
     * Test case for patchPatchProject
     *
     * Update an existing project.
     *
     */
    public function testPatchPatchProject()
    {
    }

    /**
     * Test case for postPostProject
     *
     * Creates a new project.
     *
     */
    public function testPostPostProject()
    {
    }

    /**
     * Test case for postPostProjectRate
     *
     * Adds a new rate to a project.
     *
     */
    public function testPostPostProjectRate()
    {
    }
}
