<?php
/**
 * TimesheetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kimai - API
 *
 * JSON API for the Kimai time-tracking software. Read our [API documentation](https://www.kimai.org/documentation/rest-api.html) and download the [Open API definition](doc.json) to import into your API client.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TimesheetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TimesheetApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteDeleteTimesheet
     *
     * Delete an existing timesheet record.
     *
     */
    public function testDeleteDeleteTimesheet()
    {
    }

    /**
     * Test case for getActiveTimesheet
     *
     * Returns the collection of active timesheet records.
     *
     */
    public function testGetActiveTimesheet()
    {
    }

    /**
     * Test case for getGetTimesheet
     *
     * Returns one timesheet record.
     *
     */
    public function testGetGetTimesheet()
    {
    }

    /**
     * Test case for getGetTimesheets
     *
     * Returns a collection of timesheet records (which are visible to the user).
     *
     */
    public function testGetGetTimesheets()
    {
    }

    /**
     * Test case for getRecentTimesheet
     *
     * Returns the collection of recent user activities.
     *
     */
    public function testGetRecentTimesheet()
    {
    }

    /**
     * Test case for getRestartTimesheetGet
     *
     * Restarts a previously stopped timesheet record for the current user.
     *
     */
    public function testGetRestartTimesheetGet()
    {
    }

    /**
     * Test case for getStopTimesheetGet
     *
     * Stops an active timesheet record..
     *
     */
    public function testGetStopTimesheetGet()
    {
    }

    /**
     * Test case for patchAppApiTimesheetMeta
     *
     * Sets the value of a meta-field for an existing timesheet..
     *
     */
    public function testPatchAppApiTimesheetMeta()
    {
    }

    /**
     * Test case for patchDuplicateTimesheet
     *
     * Duplicates an existing timesheet record.
     *
     */
    public function testPatchDuplicateTimesheet()
    {
    }

    /**
     * Test case for patchExportTimesheet
     *
     * Switch the export state of a timesheet record to (un-)lock it.
     *
     */
    public function testPatchExportTimesheet()
    {
    }

    /**
     * Test case for patchPatchTimesheet
     *
     * Update an existing timesheet record.
     *
     */
    public function testPatchPatchTimesheet()
    {
    }

    /**
     * Test case for patchRestartTimesheet
     *
     * Restarts a previously stopped timesheet record for the current user.
     *
     */
    public function testPatchRestartTimesheet()
    {
    }

    /**
     * Test case for patchStopTimesheet
     *
     * Stops an active timesheet record..
     *
     */
    public function testPatchStopTimesheet()
    {
    }

    /**
     * Test case for postPostTimesheet
     *
     * Creates a new timesheet record.
     *
     */
    public function testPostPostTimesheet()
    {
    }
}
